# Get-ChildItem -Recurse -Depth 2 -File | Select-Object FullName
# mkdocs gh-deploy
# mkdocs serve | build

site_name: FrontEnd Notes (lekhraj Dinkar)
site_description: Technical Documentation
site_author: lekhraj Dinkar

# Navigation based on your Notes folder
nav:
    - Angular 2025:
          - Kick Off: 01_ng/000_kick_off.md
          - NG Evolution:
                - 2025 Overview: 01_ng/000_ng_evolution-2025.md
                - NG14: 01_ng/000_ng_evolution-ng14.md
                - NG16: 01_ng/000_ng_evolution-ng16.md
                - NG17: 01_ng/000_ng_evolution-ng17.md
                - NG6: 01_ng/000_ng_evolution-ng6.md
          - Modules:
                - NgModule: 01_ng/001_01_NgModule.md
                - Fundamentals: 01_ng/002_01_Fundamentals.md
                - Directives: 01_ng/002_02_Directives.md
                - Services: 01_ng/002_03_Services.md
                - Routing Module: 01_ng/002_04_RoutingModule.md
                - Pipes: 01_ng/002_05_Pipes.md
          - RxJs & Observables: 01_ng/003_01_RxJs_Observable.md
          - Animation: 01_ng/004_01_Animation.md
          - Forms:
                - Template Driven: 01_ng/005_01_Forms_TD.md
                - Reactive: 01_ng/005_02_Forms_Reactive.md
          - HttpClient Module: 01_ng/006_httpClientModule.md
          - NgRX / Redux: 01_ng/007_NgRX_redux.md
          - Deployment: 01_ng/008_Deployment.md
          - Questions: 01_ng/100_Question_1.md

    - JavaScript 2021:
          - ES6: 02_js/007_JS_ES6.md
          - Core Concepts:
                - Execution Stack: 02_js/001_JS_CORE-1-Execution-Stack.md
                - Event Loop: 02_js/001_JS_CORE-2-Event-loop.md
                - Closure & IIFE: 02_js/001_JS_CORE-3-CLOSURE+IIFE.md
                - Promise: 02_js/001_JS_CORE-4-PROMISE.md
                - Data Types & Fundamentals: 02_js/001_JS_CORE-5-DataType+Fundamental.md
                - Arrays: 02_js/002_JS_ARRAYS.md
          - OLD:
              - AJAX: 02_js/006_JS_AJAX.md
              - object Part 1: 02_js/002_JS_ES-5-old-OBJECTS-1.md
              - object Part 2: 02_js/002_JS_ES-5-old-OBJECTS-2.md
              - DOM Concepts: 02_js/005_JS_DOM-1-concepts.md
              - Events: 02_js/004_JS_Events.md
              #- Game Programming: 02_js/005_JS_DOM-2-GAME-PRG.md

    - TypeScript 2021:
          - Kickoff: 03_ts/00_kickoff.md
          - Typing: 03_ts/01_typing.md

    - CSS & HTML (2018 OLD):
          - Kickoff: 04_css_html/001_KickOff.md
          - Selectors: 04_css_html/002_selectors.md
          - Box Model: 04_css_html/003_Box_Model.md
          - Pseudo Selectors: 04_css_html/004_pseudo-selectors.md
          - Positioning: 04_css_html/005_Position.md
          - Modern Web Design: 04_css_html/100_00_Modern_web_design.md
          - Code Structure:
                - Header: 04_css_html/100_01_Code_Header.md
                - Section: 04_css_html/100_03_Code_Section.md
                - Footer: 04_css_html/100_04_code_Footer.md
          #- Advanced Images:
              #- Part 1: 04_css_html/006_ADVNC_IMAGES-1.md
              #- Part 2: 04_css_html/006_ADVNC_IMAGES-2.md
theme:
  font:
    text: Roboto
    code: Roboto Mono
  name: material
  features:
    - navigation.tabs
    - navigation.sections
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: orange
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: green

extra_css:
  - mkdocs.css

repo_url: https://github.com/lekhrajdinkar/01-front-end-pack
repo_name: GitHub
edit_uri: edit/main/Notes/

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

plugins:
    - search
    - awesome-pages
    - redirects
